# Site settings
title: Jonathan Torres | Web Developer
email: jonathantorres41@gmail.com
description: Personal website of Jonathan Torres. A Web Developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: torres_jonathan
github_username:  jonathantorres
host: 0.0.0.0

# Build settings
markdown: kramdown

kramdown:
  input: GFM
